version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ENV=production
    volumes:
      - .:/app
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge
